version: '3.4'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - /volumes/mongodb:/data/db
    container_name: mongodb-live

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "cqrs_query"
      POSTGRES_USER: "jeanfernandes"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "./volumes/postgres/:/data/db"
    container_name: pg-live

  rabbitMQ:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq-live
    volumes:
      - "./enabled_plugins:/data/rabbitmq/enabled_plugins"

