server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/matriculas_query
    username: jeanfernandes
    password: admin
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
