server:
  port: 8081

spring:

  flyway:
    schemas: cqrs_query
    url: jdbc:postgresql://localhost:5432/cqrs_query
    enabled: true
    migrate: true
    locations: classpath:db/migration

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cqrs_query
    username: jeanfernandes
    password: admin
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
